import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { getSiteConfig } from "@/lib/content";
import { Mail, Phone, MapPin, MessageCircle, ArrowUpRight } from "lucide-react";
export default async function ContactPage({searchParams}:{searchParams:Promise<{aanbod?:string}>}) {
 const config=getSiteConfig(); const {aanbod}=await searchParams;
 const subject=aanbod ? `Vraag over ${aanbod}` : 'Kennismaken met PuurGeeske';
 const whatsapp=`${config.bookingUrl}?text=${encodeURIComponent(`Hi Geeske, ik wil graag meer weten${aanbod ? ` over ${aanbod}` : ' over je aanbod'}.`)}`;
 return <div className="min-h-screen bg-background"><Navbar/><main className="contact-main container mx-auto px-6 md:px-12 pt-40 pb-24"><div className="section-heading"><div><p className="eyebrow">Contact & afspraken</p><h1>Laten we <em>verbinden.</em></h1></div><p>Een vraag, een eerste kennismaking of een afspraak. Je bent welkom.</p></div><div className="contact-layout"><div className="contact-invite"><span className="eyebrow">Rechtstreeks met Geeske</span><h2>Een klein bericht.<br/>Een mooie eerste stap.</h2><p>{aanbod ? `Je interesseert je voor ${aanbod}. Vertel gerust wat je zoekt.` : 'Vertel wat je nodig hebt. Samen kijken we welk moment en welke sessie bij je passen.'}</p><a href={whatsapp} target="_blank" rel="noopener noreferrer" className="action-link"><MessageCircle size={18}/>Stuur een WhatsApp<ArrowUpRight size={16}/></a><p className="text-xs mt-5">Je opent WhatsApp; je verstuurt het bericht zelf.</p></div><div className="contact-methods"><a href={`mailto:${config.email}?subject=${encodeURIComponent(subject)}`}><Mail/><span><small>E-mail</small>{config.email}</span><ArrowUpRight/></a><a href={`tel:${config.phone.replace(/\s/g,'')}`}><Phone/><span><small>Telefoon</small>{config.phone}</span><ArrowUpRight/></a><div><MapPin/><span><small>Omgeving</small>{config.address}<p>De exacte locatie spreken we samen af.</p></span></div></div></div></main><Footer/></div>;
}
